apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ocp-setup-registry
  namespace: openshift-gitops
spec:
  project: default
  sources:
    - repoURL: https://github.com/acidonper/rhoai-mlops-demo.git
      targetRevision: master
      path: mlops/argocd/ocp/setup-registry
  destination:
    server: https://kubernetes.default.svc
    namespace: "rhoai-model-registries"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
