---
kind: Secret
apiVersion: v1
metadata:
  name: registry-db-{{ $.Values.namespace.name }}-secret
  namespace: rhoai-model-registries
data:
  database-name: bWV0YWRi
  database-password: dGVzdA==
  database-user: cm9vdA==
type: Opaque