{{- include "project01.validate" . -}}
---
kind: Secret
apiVersion: v1
metadata:
  name: registry-db
  namespace: {{ $.Release.Namespace }}
data:
  database-name: bWV0YWRi
  database-password: dGVzdA==
  database-user: cm9vdA==
type: Opaque