{{- include "project01.validate" . -}}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: metadata-mysql
  namespace: {{ $.Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
