apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: data-science-onboarding
  namespace: {{ $.Values.namespace.name }}
spec:
  project: default
  sources:
    - repoURL: {{ $.Values.gitRepo.url }}
      targetRevision: {{ $.Values.gitRepo.revision }}
      path: mlops/tekton/s3
      directory:
        exclude: example-*.yaml
    - repoURL: {{ $.Values.gitRepo.url }}
      targetRevision: {{ $.Values.gitRepo.revision }}
      path: mlops/argocd/data-science-onboarding
      helm:
        releaseName: {{ $.Values.namespace.name }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ $.Values.namespace.name }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
